source 'https://rubygems.org'

gem 'capistrano', '~> 3.2.1', require: false, group: :development
gem 'colored', '~> 1.2', require: false, group: :development
gem 'launchy', '~> 2.4', require: false, group: :development
gem 'inquirer.rb', '~> 0.0.3', require: false, group: :development
