#!/bin/sh

# Source function library
. /lib/lsb/init-functions

start_services() {
{% if role_mysql is defined %}
    service mysql start
{% endif %}
{% if role_apache is defined %}
    service apache2 start
{% endif %}
{% if role_varnish is defined %}
    service varnish start
{% endif %}
{% if role_pound is defined %}
    service pound start
{% endif %}
{% if role_firewall is defined %}
    service iptables-persistent start
{% endif %}
}

stop_services() {
{% if role_mysql is defined %}
    service mysql stop
{% endif %}
{% if role_apache is defined %}
    service apache2 stop
{% endif %}
{% if role_varnish is defined %}
    service varnish stop
{% endif %}
{% if role_pound is defined %}
    service pound stop
{% endif %}
{% if role_firewall is defined %}
    service iptables-persistent stop
{% endif %}
}

restart_services() {
{% if role_mysql is defined %}
    service mysql restart
{% endif %}
{% if role_apache is defined %}
    service apache2 graceful
{% endif %}
{% if role_varnish is defined %}
    service varnish restart
{% endif %}
{% if role_pound is defined %}
    service pound restart
{% endif %}
{% if role_firewall is defined %}
    service iptables-persistent restart
{% endif %}
}

status_services() {
{% if role_mysql is defined %}
    service mysql status
{% endif %}
{% if role_apache is defined %}
    service apache2 status
{% endif %}
{% if role_varnish is defined %}
    service varnish status
{% endif %}
{% if role_pound is defined %}
    service pound status
{% endif %}
{% if role_firewall is defined %}
    service iptables-persistent status
{% endif %}
}

case "$1" in
    start)
        start_services
        ;;
    stop)
        stop_services
        ;;
    restart)
        restart_services
        ;;
    status)
        status_services
        ;;
    reboot)
        reboot
        ;;
    version)
        log_success_msg "Evolution Wordpress" "<%= pkg.version %>"
        ;;
    *)
        log_success_msg "Usage $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
